### ISSUE TITLE
line 2: ***: command not found

### ISSUE THREAD

**Issue by jramosss** [davidSchuppa/base64Secret-toFile-action#2]
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Decode secret
        uses: davidSchuppa/base64Secret-toFile-action@v1
        with:
            secret: ${{ secrets.STAGING_CERT_BASE64 }}
            filename: cert.cer
            destination-path: ~/
```

This is the full trace

```
Run davidSchuppa/base64Secret-toFile-action@v1
  with:
    secret: ***
    filename: cert.cer
    destination-path: ~/
Run echo ***
  echo ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  *** > ./cert.cer.tmp
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
***
/home/runner/work/_temp/3da1a4ae-4fae-4dbf-91a
```

My secret is just a plain base 64 string
